name: news__app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  intl: ^0.20.2
  floor: ^1.5.0
  retrofit: ^4.9.2
  flutter_hooks: ^0.21.3+1
  cached_network_image: ^3.4.1
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
        - asset: assets/fonts/Muli-Light.ttf
        - asset: assets/fonts/Muli-Italic.ttf
        - asset: assets/fonts/Muli-LightItalic.ttf
